### ISSUE TITLE
请问这个模型怎么用，有没example呢？多谢

### ISSUE THREAD

**Issue by nlpchen** [Dhaizei/huggingface#1]
https://huggingface.co/DDDSSS/translation_en-zh
请问这个模型怎么用，
可以发个demo给我吗？想本地运行。nlp_chen@163.com

**Comment by nlpchen** [comment]
例如，各个lib的版本是多少呢？transformers的版本是多少？ @Dhaizei

**Comment by Dhaizei** [comment]
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, pipeline
parser.add_argument('--device', default="cpu", type=str, help='"cuda:1"、"cuda:2"……')
mode_name = opt.model
device = opt.device
model = AutoModelForSeq2SeqLM.from_pretrained(mode_name)
tokenizer = AutoTokenizer.from_pretrained(mode_name)
translation = pipeline("translation_en_to_zh", model=model, tokenizer=tokenizer,
                       torch_dtype="float", device_map=True,device=device)
x=["If nothing is detected and there is a config.json file, it’s assumed the library is transformers.","By looking into the presence of files such as *.nemo or *saved_model.pb*, the Hub can determine if a model is from NeMo or Keras."]
re = translation(x, max_length=512)
print('翻译为：' ,re)

**Comment by Dhaizei** [comment]
安装最近的版本就可以了

**Comment by Dhaizei** [comment]
mode_name = "DDDSSS/translation_en-zh" 或者 参考https://huggingface.co/Helsinki-NLP/opus-mt-en-zh  他的，我主要是在他的模型上进行微调的，你可以参考我上传的model card

**Comment by Dhaizei** [comment]
demo.py文件已经发你了，查收下

**Comment by nlpchen** [comment]
wow~ ⊙o⊙感恩的心，我试试。

> demo.py文件已经发你了，查收下

**Comment by nlpchen** [comment]
![image](https://github.com/Dhaizei/huggingface/assets/135082718/56105cf8-d4f2-4da6-85f5-f321b5a29841)
请问这个错误怎么解决呢？

**Comment by Dhaizei** [comment]
应该是因为你的网络不行导致的，因为这个demo我自己在我本地上试过了，可以运行的
你可以在官网上直接把模型下载下来，通过本地运行

**Comment by nlpchen** [comment]
不知道是不是版本不对还是，可以看一下你的环境吗？pip freeze或者pip list一下？
(torch1.9.0) D:\translator\translation_en-zh>python demo.py
C:\Users\Lenovo\.conda\envs\torch1.9.0\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Lenovo\.conda\envs\torch1.9.0\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Lenovo\.conda\envs\torch1.9.0\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    model = AutoModelForSeq2SeqLM.from_pretrained(mode_name)
  File "C:\Users\Lenovo\.conda\envs\torch1.9.0\lib\site-packages\transformers\models\auto\auto_factory.py", line 464, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "C:\Users\Lenovo\.conda\envs\torch1.9.0\lib\site-packages\transformers\modeling_utils.py", line 2184, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "C:\Users\Lenovo\.conda\envs\torch1.9.0\lib\site-packages\transformers\modeling_utils.py", line 397, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "C:\Users\Lenovo\.conda\envs\torch1.9.0\lib\site-packages\safetensors\torch.py", line 261, in load_file
    result[k] = f.get_tensor(k)
AttributeError: module 'torch' has no attribute 'frombuffer'
![image](https://github.com/Dhaizei/huggingface/assets/135082718/f60e1016-af93-40bf-8aaa-57ef610f7b7d)

不知道是不是版本不对还是，可以看一下你的环境吗？
我的pip freeze如下，
absl-py==0.15.0
aiofiles==23.1.0
aiohttp==3.7.4.post0
aitextgen==0.5.2
altair==4.2.0
amqp==5.0.9
anyio==3.3.4
argcomplete @ file:///tmp/build/80754af9/argcomplete_1618920853202/work
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///C:/ci/argon2-cffi-bindings_1644569848815/work
asgiref==3.5.0
astor==0.8.1
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
async-timeout==3.0.1
attrs @ file:///C:/b/abs_09s3y775ra/croot/attrs_1668696195628/work
Automat==22.10.0
Babel==2.9.1
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.zoneinfo==0.2.1
base58==2.1.1
bce-python-sdk==0.8.83
beautifulsoup4==4.10.0
bert-extractive-summarizer==0.10.1
bert4keras==0.11.3
billiard==3.6.4.0
bleach @ file:///tmp/build/80754af9/bleach_1628110601003/work
blinker==1.4
blis==0.4.1
bminf==0.0.5
boto3==1.0.0
botocore==1.0.0
Bottleneck @ file:///C:/Windows/Temp/abs_3198ca53-903d-42fd-87b4-03e6d03a8381yfwsuve8/croots/recipe/bottleneck_1657175565403/work
breadability==0.1.20
bs4==0.0.1
cached-property==1.5.2
cachetools==4.2.4
catalogue==1.0.2
celery==5.2.3
certifi==2022.12.7
cffi @ file:///C:/b/abs_49n3v2hyhr/croot/cffi_1670423218144/work
chardet==3.0.4
charset-normalizer==3.1.0
click==8.0.0
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
colorama==0.4.6
colorlog==6.7.0
commonmark==0.9.1
confection==0.0.4
constantly==15.1.0
cpm-kernels==1.0.11
cryptography==41.0.1
cssselect==1.2.0
cupy-cuda111==9.5.0
cycler==0.10.0
cymem==2.0.7
Cython==0.29.23
datasets==2.13.1
decorator @ file:///tmp/build/80754af9/decorator_1632776554403/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
Deprecated==1.2.13
dill==0.3.6
Django==2.2.5
django-cors-headers==3.5.0
dnspython==2.2.1
docopt==0.6.2
docutils==0.15.2
elasticsearch==7.16.0
emoji==1.6.1
entrypoints @ file:///C:/ci/entrypoints_1649926659561/work
et-xmlfile @ file:///D:/rewriting/nlp_xiaojiang/pcks/et_xmlfile-1.1.0.tar.gz
evaluate==0.4.0
eventlet==0.33.0
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
fastapi==0.75.0
fastrlock==0.8
fasttext==0.9.1
ffmpy==0.3.0
filelock==3.12.0
fire==0.4.0
Flask==2.1.2
Flask-Babel==2.0.0
Flask-Cors==3.0.10
flit_core @ file:///opt/conda/conda-bld/flit-core_1644941570762/work/source/flit_core
flower==1.0.0
fsspec==2023.1.0
future==0.18.2
futures==2.2.0
gast==0.2.2
gensim==4.1.0
gevent==21.12.0
gitdb==4.0.9
GitPython==3.1.27
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googletrans==4.0.0rc1
gradio==3.24.1
gradio_client==0.0.8
greenlet==1.1.2
grpcio==1.41.1
gunicorn==20.1.0
h11==0.9.0
h2==3.2.0
h5py==2.10.0
hanlp-downloader @ file:///D:/rewriting/pyhanlp/pcks/hanlp_downloader-0.0.25.tar.gz
hpack==3.0.0
hstspreload==2023.1.1
httpcore==0.9.1
httpx==0.13.3
huggingface-hub==0.15.1
humanize==4.0.0
hyperframe==5.2.0
hyperlink==21.0.0
idna==2.10
importlib-metadata==6.6.0
importlib-resources==5.12.0
incremental==22.10.0
ipykernel @ file:///C:/ci/ipykernel_1596208728219/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/Windows/TEMP/abs_45b5zb1l7q/croots/recipe/ipython_1659529855872/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets==7.7.1
isodate==0.6.1
itemadapter==0.7.0
itemloaders==1.0.6
itsdangerous==2.0.1
jedi @ file:///C:/ci/jedi_1644297241925/work
jiayan==0.0.21
jieba==0.42.1
jieba-fast==0.53
Jinja2==3.1.2
jiojio==1.2.4
jionlp==1.4.35
jmespath==0.7.1
joblib==1.2.0
JPype1 @ file:///D:/rewriting/nlp_xiaojiang/pcks/JPype1-1.3.0-cp37-cp37m-win_amd64.whl
json5==0.9.6
jsonschema==4.17.3
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1630690655192/work
jupyter-server==1.11.2
jupyter_core @ file:///C:/b/abs_b8r5lb5eus/croot/jupyter_core_1668084445779/work
jupyterlab==3.2.2
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server==2.8.2
jupyterlab-widgets==1.1.1
kenlm @ https://github.com/kpu/kenlm/archive/master.zip
Keras==2.3.1
Keras-Applications==1.0.8
keras-embed-sim==0.10.0
keras-layer-normalization==0.16.0
keras-multi-head==0.29.0
keras-pos-embd==0.13.0
keras-position-wise-feed-forward==0.8.0
Keras-Preprocessing==1.1.2
keras-self-attention==0.51.0
keras-transformer==0.40.0
kiwisolver==1.3.2
kombu==5.2.3
LAC==2.1.2
langcodes==3.3.0
latex2mathml @ file:///D:/rewriting/chatgpt_academic/pcks/latex2mathml-3.75.2-py3-none-any.whl
linkify-it-py==2.0.0
ltp==4.1.5.post2
lxml==4.9.2
Markdown==3.3.4
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.4.3
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mdit-py-plugins==0.3.3
mdtex2html @ file:///D:/rewriting/chatgpt_academic/pcks/mdtex2html-1.2.0-py3-none-any.whl
mdurl==0.1.2
memory-profiler==0.60.0
mistune @ file:///C:/ci/mistune_1594373272338/work
mkl-fft==1.3.0
mkl-random==1.1.1
mkl-service==2.3.0
multidict==5.2.0
multiprocess==0.70.14
murmurhash==1.0.9
nbclassic==0.3.4
nbconvert==5.5.0
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx==2.6.3
nltk==3.6.2
notebook @ file:///C:/Windows/TEMP/abs_79abr1_60s/croots/recipe/notebook_1659083661851/work
numexpr @ file:///C:/ci/numexpr_1614798720432/work
numpy==1.18.2
oauthlib==3.1.1
openai==0.27.4
opencc-python-reimplemented==0.1.6
openpyxl @ file:///D:/rewriting/nlp_xiaojiang/pcks/openpyxl-3.1.2.tar.gz
opt-einsum==3.3.0
orjson==3.8.10
outcome==1.1.0
packaging==23.1
paddle-bfloat==0.1.7
paddle2onnx==1.0.6
paddlefsl==1.1.0
paddlenlp==2.5.2
paddlepaddle==2.3.1
pandas==1.3.4
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parsel==1.7.0
parso @ file:///tmp/build/80754af9/parso_1617223946239/work
pathos==0.3.0
pathy==0.10.1
pdf2image==1.16.0
pdf2pptx==1.0.3
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.3.2
Pinyin2Hanzi==0.1.1
pinyinsplit==0.1.4
pkgutil_resolve_name==1.3.10
plac==0.9.6
portalocker==2.7.0
pox==0.3.2
ppft==1.7.6.6
preshed==3.0.8
prettytable==0.7.2
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1623189609245/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
Protego==0.2.1
protobuf==3.19.0
psutil==5.9.1
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
pyarrow==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.8.0
pycorrector==0.4.2
pycountry==22.3.5
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycryptodome==3.17
pydantic==1.10.7
pydeck==0.7.1
pyDeprecate==0.3.1
PyDispatcher==2.0.6
pydub==0.25.1
PyExecJS==1.5.1
Pygments @ file:///tmp/build/80754af9/pygments_1629234116488/work
pygtrie==2.4.2
Pympler==1.0.1
PyMuPDF==1.19.6
PyMySQL==1.0.2
pyOpenSSL==21.0.0
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pypinyin==0.46.0
pyrouge==0.1.3
pyrsistent @ file:///C:/ci/pyrsistent_1636093257833/work
python-crfsuite==0.9.8
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-Levenshtein @ file:///D:/rewriting/nlp_xiaojiang/pcks/python_Levenshtein-0.12.2-cp37-cp37m-win_amd64.whl
python-louvain==0.16
python-markdown-math @ file:///D:/rewriting/chatgpt_academic/pcks/python_markdown_math-0.8-py3-none-any.whl
python-multipart==0.0.6
python-pptx==0.6.21
pytorch-lightning==1.4.9
pytorch-pretrained-bert==0.6.2
pytorch-transformers==1.2.0
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
pywin32==305.1
pywinpty @ file:///C:/ci_310/pywinpty_1644230983541/work/target/wheels/pywinpty-2.0.2-cp37-none-win_amd64.whl
PyYAML==6.0
pyzmq @ file:///C:/ci/pyzmq_1657597757589/work
Qt.py==1.3.7
queuelib==1.6.2
rdflib==6.2.0
redis==4.1.4
regex==2022.10.31
requests==2.29.0
requests-file==1.5.1
requests-oauthlib==1.3.0
responses==0.18.0
rfc3986==1.5.0
rich==12.4.4
rjieba==0.1.11
roformer==0.4.3
rouge==1.0.1
rouge-chinese==1.0.3
rouge-score==0.0.4
rsa==4.7.2
s3transfer==0.3.7
sacrebleu==2.3.1
sacremoses==0.0.46
safetensors==0.3.1
scikit-learn==1.0.2
scipy==1.7.3
Scrapy==2.8.0
selenium==4.0.0
semantic-version==2.10.0
semver==2.13.0
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
sentence-transformers==2.2.2
sentencepiece==0.1.96
seqeval==1.2.2
service-identity==21.1.0
# Editable install with no version control (simcse==0.4)
-e c:\users\lenovo\.conda\envs\torch1.9.0\lib\site-packages
six @ file:///tmp/build/80754af9/six_1623709665295/work
sklearn==0.0
smart-open==6.3.0
smmap==5.0.0
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.3
spacy==2.3.1
spacy-legacy==3.0.12
spacy-loggers==1.0.4
spacy-pkuseg==0.0.30
sqlparse==0.4.2
srsly==1.0.6
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
starlette==0.17.1
streamlit==1.7.0
summa==1.2.0
sumy==0.11.0
synonyms @ file:///D:/rewriting/eda_nlp_for_Chinese/pcks/synonyms-3.10.2.tar.gz
tabulate==0.9.0
tb-nightly==2.8.0a20211025
tensorboard==2.0.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.5.1
tensorflow==2.0.1
tensorflow-estimator==2.0.1
termcolor==1.1.0
terminado @ file:///C:/b/abs_25nakickad/croot/terminado_1671751845491/work
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
textrank4zh==0.3
thinc==7.4.1
threadpoolctl==3.1.0
thulac==0.2.1
tldextract==3.4.0
tokenizers==0.13.3
toml==0.10.2
toolz==0.11.2
torch==1.9.0+cu111
torchaudio==0.9.0
torchmetrics==0.6.0
torchtext==0.14.1
torchvision==0.10.0+cu111
tornado @ file:///C:/ci/tornado_1662476933490/work
tqdm==4.65.0
traitlets @ file:///tmp/build/80754af9/traitlets_1632522747050/work
transformers==4.24.0
translators==5.7.0
trio==0.19.0
trio-websocket==0.9.2
Twisted==22.10.0
twisted-iocpsupport==1.0.2
typer==0.7.0
typing-extensions==3.10.0.2
tzdata==2022.1
tzlocal==4.2
uc-micro-py==1.0.1
urllib3==1.26.15
uvicorn==0.17.6
uwsgitop==0.11
validators==0.20.0
vine==5.0.0
visualdl==2.4.2
w3lib==1.22.0
wasabi==0.10.1
watchdog==2.1.9
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
websocket-client==1.2.1
websockets==11.0.1
Werkzeug==2.0.2
widgetsnbextension==3.6.1
wincertstore==0.2
wordcloud==1.8.1
wrapt==1.13.3
wsproto==1.0.0
xlrd==2.0.1
XlsxWriter==3.0.3
xpinyin==0.7.6
xxhash==3.2.0
yarl==1.7.0
you-get==0.4.1650
zh-core-web-md @ file:///D:/source_recommend/source_recommand/pcks/zh_core_web_md-3.2.0-py3-none-any.whl
zipfile36==0.1.3
zipp==3.15.0
zope.event==4.5.0
zope.interface==5.4.0

**Comment by Dhaizei** [comment]
我装的指令如下：
        pip install torch torchvision torchaudio
        pip install gevent
        pip install -r requirements.txt
其中requirem.txt的内容是：
        aniso8601==9.0.1
        certifi==2022.12.7
        charset-normalizer==3.1.0
        click==8.1.3
        colorama==0.4.6
        filelock==3.9.1
        Flask==2.2.3
        Flask-RESTful==0.3.9
        huggingface-hub==0.13.2
        idna==3.4
        importlib-metadata==6.0.0
        itsdangerous==2.1.2
        Jinja2==3.1.2
        MarkupSafe==2.1.2
        numpy==1.24.2
        packaging==23.0
        Pillow==9.4.0
        pytz==2022.7.1
        PyYAML==6.0
        regex==2022.10.31
        requests==2.28.2
        sentencepiece==0.1.97
        six==1.16.0
        tokenizers==0.13.2
        tqdm==4.65.0
        transformers==4.26.1
        typing_extensions==4.5.0
        urllib3==1.26.15
        Werkzeug==2.2.3
        zipp==3.15.0

就是直接安装pytorch最新版本和transformer最新版本而已。

**Comment by Dhaizei** [comment]
看了下你的环境，装的比较杂，不太建议好几个框架在一个环境下，建议重新创建一个虚拟环境吧~

**Comment by Dhaizei** [comment]
以下是我的freeze：
absl-py==1.4.0
accelerate==0.19.0
addict==2.4.0
aiohttp==3.8.4
aiosignal==1.3.1
aniso8601==9.0.1
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-timeout==4.0.2
attrs==23.1.0
autograd==1.6.2
backcall==0.2.0
beautifulsoup4==4.12.2
bitsandbytes==0.38.1
bleach==6.0.0
cachetools==5.3.1
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cma==2.7.0
colorama==0.4.6
coloredlogs==15.0.1
comm==0.1.3
ConfigArgParse==1.5.3
contourpy==1.1.0
ctranslate2==3.15.0
cycler==0.11.0
datasets==2.9.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.6
evaluate==0.4.0
executing==1.2.0
fastjsonschema==2.16.3
filelock==3.9.1
Flask==2.2.3
Flask-RESTful==0.3.9
flatbuffers==23.5.26
fonttools==4.40.0
fqdn==1.5.1
frozenlist==1.3.3
fsspec==2023.5.0
future==0.18.3
gevent==22.10.2
google-auth==2.19.1
google-auth-oauthlib==1.0.0
greenlet==2.0.2
grpcio==1.54.2
huggingface-hub==0.13.2
humanfriendly==10.0
idna==3.4
importlib-metadata==6.0.0
interchange==2021.0.4
ipykernel==6.22.0
ipython==8.12.0
ipython-genutils==0.2.0
ipywidgets==8.0.6
isoduration==20.11.0
itsdangerous==2.1.2
jedi==0.18.2
jieba==0.42.1
Jinja2==3.1.2
joblib==1.2.0
jsonpointer==2.3
jsonschema==4.17.3
jstyleson==0.0.2
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.5.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
lxml==4.9.2
Markdown==3.4.3
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mistune==2.0.5
monotonic==1.6
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
natsort==8.4.0
nbclassic==1.0.0
nbclient==0.7.4
nbconvert==7.4.0
nbformat==5.8.0
nest-asyncio==1.5.6
networkx==2.8.2
ninja==1.10.2.4
nltk==3.8.1
nncf==2.5.0
notebook==6.5.4
notebook_shim==0.2.3
numpy==1.23.5
oauthlib==3.2.2
onnx==1.14.0
onnxruntime==1.15.1
OpenCC==1.1.1
opencv-python==4.7.0.72
OpenNMT-py==2.3.0
openvino==2023.0.0
openvino-dev==2023.0.0
openvino-telemetry==2023.0.0
optimum @ git+https://github.com/huggingface/optimum.git@282dd385bb1e8c9ea62edcc19bd04f2b50855eac
optimum-intel==1.9.2
packaging==23.0
pandas==2.0.1
pandocfilters==1.5.0
pansi==2020.7.3
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.2.0
portalocker==2.7.0
prometheus-client==0.16.0
prompt-toolkit==3.0.38
protobuf==3.20.2
psutil==5.9.5
pure-eval==0.2.2
py2neo==2021.2.3
pyarrow==12.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydot==1.4.2
Pygments==2.15.1
pymoo==0.5.0
pyonmttok==1.37.1
pyparsing==2.4.7
pyreadline3==3.4.1
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2022.7.1
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.2
qtconsole==5.4.3
QtPy==2.3.1
regex==2022.10.31
requests==2.28.2
requests-oauthlib==1.3.1
responses==0.18.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rsa==4.9
sacrebleu==2.3.1
sacremoses==0.0.53
scikit-learn==1.2.2
scipy==1.10.1
Send2Trash==1.8.2
sentencepiece==0.1.97
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data==0.6.2
sympy==1.12
tabulate==0.9.0
tensorboard==2.13.0
tensorboard-data-server==0.7.0
terminado==0.17.1
texttable==1.6.7
threadpoolctl==3.1.0
tinycss2==1.2.1
tokenizers==0.13.2
torch==2.0.1+cu117
torchaudio==2.0.2
torchtext==0.5.0
torchvision==0.15.2
tornado==6.3.1
tqdm==4.65.0
traitlets==5.9.0
transformers==4.26.1
typing_extensions==4.5.0
tzdata==2023.3
uri-template==1.2.0
urllib3==1.26.15
waitress==2.1.2
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.3
widgetsnbextension==4.0.7
xxhash==3.2.0
yarl==1.9.2
zipp==3.15.0
zope.event==4.6
zope.interface==6.0

**Comment by nlpchen** [comment]
可以了，多谢，看了一下效果还不错，请问训练的代码和数据的样例可以分享一下吗？学习学习。
如下是我的环境
![image](https://github.com/Dhaizei/huggingface/assets/135082718/9dcdac21-9c3e-4987-9124-5918575ce6a4)
!pip install pip install gevent
!pip install pip install torch torchvision torchaudio
!pip install transformers==4.26.1

**Comment by Dhaizei** [comment]
参考&nbsp;https://huggingface.co/DDDSSS/translation_en-zh




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月6日(星期四) 上午9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Dhaizei/huggingface] 请问这个模型怎么用，有没example呢？多谢 (Issue #1)





 
可以了，多谢，看了一下效果还不错，请问训练的代码和数据的样例可以分享一下吗？学习学习。
 如下是我的环境
 
 !pip install pip install gevent
 !pip install pip install torch torchvision torchaudio
 !pip install transformers==4.26.1

**Comment by Dhaizei** [comment]
数据样例参考[DDDSSS/en-zh-dataset](https://huggingface.co/datasets/DDDSSS/en-zh-dataset)
